#!/bin/bash
# QUICK START REFERENCE

echo "═══════════════════════════════════════════════════════════════"
echo "  RAG ATS Resume Builder - Quick Start"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📋 WORKFLOW:"
echo ""
echo "  1️⃣  PRE-INGEST (One-time per resume)"
echo "      jupyter notebook ingest_profile.ipynb"
echo "      → Load your PDF/URL/text"
echo "      → Save as profile (e.g., 'my_profile')"
echo ""
echo "  2️⃣  START APP (Keep running)"
echo "      ./start.sh"
echo "      → Frontend: http://localhost:3000"
echo "      → Backend:  http://localhost:8000"
echo ""
echo "  3️⃣  GENERATE RESUMES (Repeat as needed)"
echo "      → Open http://localhost:3000"
echo "      → Enter profile name: my_profile"
echo "      → Fill job details"
echo "      → Click 'Generate Resume'"
echo "      → Download PDF"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📁 KEY FILES:"
echo "   ingest_profile.ipynb        → Profile creation"
echo "   profile_cache/              → Stored profiles & embeddings"
echo "   start.sh                    → Start both services"
echo "   PROFILE_MANAGEMENT.md       → Detailed guide"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "💡 TIPS:"
echo "   • Profile name = name you gave when ingesting"
echo "   • Multiple profiles? Create multiple in notebook"
echo "   • Profiles are stored locally (no uploads)"
echo "   • One ingest = unlimited resume generations"
echo ""
echo "═══════════════════════════════════════════════════════════════"
